server:
  port: "${VIRTUAL_PORT:8081}"

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: "${PROFILE: dev}"
  application:
    name: spaces-service

keycloak:
  realm: Application
  auth-server-url: https://keycloak.alphabibber.com/auth/
  ssl-required: external
  resource: spaces-service
  credentials.secret: 9efde360-40e6-467c-bfdd-0b747d6e27ac
  use-resource-role-mappings: true
  bearer-only: true