server:
  port: ${VIRTUAL_PORT}

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE}
  application:
    name: spaces-service
  datasource:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000

keycloak:
  realm: Application
  auth-server-url: ${KEYCLOAK_PROTOCOL}://${KEYCLOAK_URL}/auth/
  ssl-required: external
  resource: spaces-service
  credentials.secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  bearer-only: true