version: '3'
services:
  db:
    container_name: posthog_db
    environment:
      POSTGRES_DB: posthog
      POSTGRES_PASSWORD: ${POSTHOG_DATA_PW}
      POSTGRES_USER: posthog
    image: postgres:13-alpine
    volumes:
      - posthog-data:/var/lib/postgresql/data

  redis:
    container_name: posthog_redis
    image: redis:6-alpine

  web:
    container_name: posthog_web
    depends_on:
      - db
      - redis
    environment:
      - VIRTUAL_HOST=${POSTHOG_URL}
      - LETSENCRYPT_HOST=${POSTHOG_URL}
      - VIRTUAL_PORT=${POSTHOG_PORT}
      - IS_BEHIND_PROXY=true
      - TRUST_ALL_PROXIES=true
      - DATABASE_URL=postgres://posthog:${POSTHOG_DATA_PW}@db:5432/posthog
      - REDIS_URL=redis://redis:6379/
      - SECRET_KEY=${POSTHOG_KEY}
      - IS_DOCKER=true
    image: posthog/posthog:latest
    links:
      - db:db
      - redis:redis
    networks:
      - application

volumes:
  posthog-data:
    external: true

networks:
  application:
    driver: bridge
    external: true