version: "2"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - VIRTUAL_HOST=${PROMETHEUS_URL}
      - LETSENCRYPT_HOST=${PROMETHEUS_URL}
      - VIRTUAL_PORT=${PROMETHEUS_PORT}
    volumes:
      - /home/git_environment/NotZoom/keycloak/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
    - application

#       starts on 9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - VIRTUAL_HOST=${GRAFANA_URL}
      - LETSENCRYPT_HOST=${GRAFANA_URL}
      - VIRTUAL_PORT=${GRAFANA_PORT}
    networks:
      - application


volumes:
  prometheus:
    external: true

networks:
  application:
    driver: bridge
    external: true
