version: "2"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_SIGNAL_URL=${WEBSOCKET_URL}
        - REACT_APP_SIGNAL_PORT=${WEBSOCKET_URL}
        - REACT_APP_SPACES_URL=${SPACES_URL}
        - REACT_APP_AUTH_URL=${AUTH_URL}
    environment:
      - VIRTUAL_HOST=${FRONTEND_URL}
      - LETSENCRYPT_HOST=${FRONTEND_URL}
    networks:
      - application

  nginx-landingpage:
    build:
      context: ./landingpage
      dockerfile: ./Dockerfile
    environment:
        - VIRTUAL_HOST=${LANDINGPAGE_URL}
        - LETSENCRYPT_HOST=${LANDINGPAGE_URL}
    networks:
      - application

  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
      args:
        - VIRTUAL_PORT=${AUTH_PORT}
    environment:
      - VIRTUAL_HOST=${AUTH_URL}
      - LETSENCRYPT_HOST=${AUTH_URL}
      - VIRTUAL_PORT=${AUTH_PORT}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
    networks:
      - application

  websocket-service:
    build:
      context: ./websocket-service
      dockerfile: ./Dockerfile
      args:
        - SPACES_URL=${SPACES_URL}
        - VIRTUAL_PORT=${WEBSOCKET_PORT}
    environment:
      - LETSENCRYPT_HOST=${WEBSOCKET_URL}
      - VIRTUAL_PORT=${WEBSOCKET_PORT}
      - VIRTUAL_HOST=${WEBSOCKET_URL}
    networks:
      - application

  spaces-service:
    build:
      context: ./spaces-service
      dockerfile: ./Dockerfile
      args:
        - VIRTUAL_PORT=${SPACES_PORT}
    environment:
      - VIRTUAL_HOST=${SPACES_URL}
      - LETSENCRYPT_HOST=${SPACES_URL}
      - VIRTUAL_PORT=${SPACES_PORT}
    networks:
      - application

  nginx-presentation:
    build:
      context: ./presentation
      dockerfile: ./Dockerfile
    environment:
      - VIRTUAL_HOST=${PRESENTATION_URL}
      - LETSENCRYPT_HOST=${PRESENTATION_URL}
    networks:
      - application

volumes:
  certs: { }
  vhost: { }
  html: { }

networks:
  application:
    driver: bridge
