version: "2"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_HOMEPAGE_URL=${HOMEPAGE_URL}
        - REACT_APP_SIGNAL_URL=${WEBSOCKET_URL}
        - REACT_APP_SIGNAL_PORT=${WEBSOCKET_PORT}
        - REACT_APP_SPACES_URL=${SPACES_URL}
        - REACT_APP_AUTH_URL=${KEYCLOAK_URL}
        - REACT_APP_FRONTEND_URL=${FRONTEND_URL}
        - REACT_APP_REALM=${KEYCLOAK_REALM}
        - REACT_APP_KEYCLOAK_CLIENT=${KEYCLOAK_FRONTEND_CLIENT}
        - REACT_APP_ACCOUNT_URL=${ACCOUNT_URL}
        - REACT_APP_SUPPORT_URL=${WIKI_URL}
        - REACT_APP_SFU_PORT=${SFU_PORT}
        - REACT_APP_SFU_URL=${HOMEPAGE_URL}
    environment:
      - VIRTUAL_HOST=${FRONTEND_URL}
      - LETSENCRYPT_HOST=${FRONTEND_URL}
    networks:
      - application

  homepage:
    container_name: homepage
    build:
      context: .
      dockerfile: ./homepage/Dockerfile
      args:
        - REACT_APP_HOMEPAGE_URL=${HOMEPAGE_URL}
        - REACT_APP_AUTH_URL=${KEYCLOAK_URL}
        - REACT_APP_FRONTEND_URL=${FRONTEND_URL}
        - REACT_APP_REALM=${KEYCLOAK_REALM}
        - REACT_APP_KEYCLOAK_CLIENT=${KEYCLOAK_FRONTEND_CLIENT}
        - REACT_APP_SUPPORT_URL=${WIKI_URL}
    environment:
      - VIRTUAL_HOST=${HOMEPAGE_URL}
      - LETSENCRYPT_HOST=${HOMEPAGE_URL}
    networks:
      - application

  wiki:
    container_name: wiki
    build:
      context: ./wiki
      dockerfile: ./Dockerfile
    environment:
      - VIRTUAL_HOST=${WIKI_URL}
      - LETSENCRYPT_HOST=${WIKI_URL}
    networks:
      - application

  websocket-service:
    container_name: websocket-service
    build:
      context: ./websocket-service
      dockerfile: ./Dockerfile
      args:
        - SPACES_URL=${SPACES_URL}
        - VIRTUAL_PORT=${WEBSOCKET_PORT}
    environment:
      - LETSENCRYPT_HOST=${WEBSOCKET_URL}
      - VIRTUAL_PORT=${WEBSOCKET_PORT}
      - VIRTUAL_HOST=${WEBSOCKET_URL}
    networks:
      - application

  spaces-service:
    container_name: spaces-service
    build:
      context: ./spaces-service
      dockerfile: ./Dockerfile
      args:
        - VIRTUAL_PORT=${SPACES_PORT}
    environment:
      - PROFILE=prod
      - VIRTUAL_HOST=${SPACES_URL}
      - LETSENCRYPT_HOST=${SPACES_URL}
      - VIRTUAL_PORT=${SPACES_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=spaces-postgres
      - DB_PORT=5432
      - DB_PASSWORD=${SPACES_DB_PASSWORD}
      - DB_NAME=db
      - DB_USER=admin
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_PROTOCOL=https
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    networks:
      - application

  account-service:
    container_name: account-service
    build:
      context: ./account-service
      dockerfile: ./Dockerfile
      args:
        - VIRTUAL_PORT=${ACCOUNT_PORT}
    environment:
      - VIRTUAL_HOST=${ACCOUNT_URL}
      - LETSENCRYPT_HOST=${ACCOUNT_URL}
      - VIRTUAL_PORT=${ACCOUNT_PORT}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ACCOUNTSERVICE_PASSWORD}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET_ACCOUNT_SERVICE}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_PROTOCOL=https
      - KEYCLOAK_REALM=Application
      - KEYCLOAK_USER=AccountService
      - GCP_PROJECT_NAME=yacht-chat
      - GCP_BUCKET_NAME=yacht-chat
      - GOOGLE_APPLICATION_CREDENTIALS=tmp/keys/yacht-chat-4cfbecf324d7.json
#      - GOOGLE_APPLICATION_CREDENTIALS=tmp/keys/yacht-chat-9b0254d39af7.json
    volumes:
#      - /Users/marc/Development/yacht-chat-9b0254d39af7.json:/tmp/keys/yacht-chat-9b0254d39af7.json
      - /tmp/keys/yacht-chat-4cfbecf324d7.json:/tmp/keys/yacht-chat-4cfbecf324d7.json
    networks:
      - application

networks:
  application:
    external: true
    driver: bridge

volumes:
  certs:
    external: true
  vhost:
    external: true
  html:
    external: true
  keycloak_postgres_data:
    external: true
  
