apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: landingpage-service
#spec:
#  selector:
#    app: landingpage-app
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: ${{LANDINGPAGE_PORT}}
#      protocol: TCP
#      name: http
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: presentation-service
#spec:
#  selector:
#    app: presentation-app
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: ${{PRESENTATION_PORT}}
#      protocol: TCP
#      name: http
#---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  selector:
    app: websocket-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: spacesservice-service
spec:
  selector:
    app: spacesservice-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081

