apiVersion: v1
kind: Service
metadata:
  name: frontend_service
spec:
  selector:
    app: frontend_app
  type: NodePort
  ports:
    - port: 80
      targetPort: ${FRONTEND_PORT}
      protocol: TCP
      name: http
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: landingpage_service
#spec:
#  selector:
#    app: landingpage_app
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: ${LANDINGPAGE_PORT}
#      protocol: TCP
#      name: http
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: presentation_service
#spec:
#  selector:
#    app: presentation_app
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: ${PRESENTATION_PORT}
#      protocol: TCP
#      name: http
#---
apiVersion: v1
kind: Service
metadata:
  name: signalingServer_service
spec:
  selector:
    app: signalingServer_app
  type: NodePort
  ports:
    - port: 80
      targetPort: ${SIGNAL_PORT}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: spacesService_service
spec:
  selector:
    app: spacesService_app
  type: NodePort
  ports:
    - port: 80
      targetPort: ${SPACES_PORT}
      protocol: TCP
      name: http
