apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-app
  type: NodePort
  ports:
    - port: 80
      targetPort: %env(int:FRONTEND_PORT)%
      protocol: TCP
      name: http
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: landingpage-service
#spec:
#  selector:
#    app: landingpage-app
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: ${{LANDINGPAGE_PORT}}
#      protocol: TCP
#      name: http
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: presentation-service
#spec:
#  selector:
#    app: presentation-app
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: ${{PRESENTATION_PORT}}
#      protocol: TCP
#      name: http
#---
apiVersion: v1
kind: Service
metadata:
  name: signalingServer-service
spec:
  selector:
    app: signalingServer-app
  type: NodePort
  ports:
    - port: 80
      targetPort: ${{SIGNAL_PORT}}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: spacesService-service
spec:
  selector:
    app: spacesService-app
  type: NodePort
  ports:
    - port: 80
      targetPort: ${{SPACES_PORT}}
      protocol: TCP
      name: http
