name: Build and Deploy to GKE

on:
  push:
    branches:
#      - main
       - devops/migrationtoGKE
       - devops/migrationtoGKEusingHELM
  
  workflow_dispatch: 

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: alphabibber-gke-prod
  GKE_ZONE: europe-west3-a
  FRONTEND_DEPLOYMENT_NAME: frontend-app
  LANDINGPAGE_DEPLOYMENT_NAME: landingpage-app
  PRESENTATION_DEPLOYMENT_NAME: presentation-app
  WEBSOCKET_DEPLOYMENT_NAME: websocket-app
  SPACES_DEPLOYMENT_NAME: spacesservice-app
  FRONTEND_IMAGE: frontend-image
  LANDINGPAGE_IMAGE: landingpage-image
  PRESENTATION_IMAGE: presentation-image
  WEBSOCKET_IMAGE: websocket-image
  SPACES_IMAGE: spaces-image
  # also used in yaml files
  GKE_FRONTEND_URL: gke.alphabibber.com
  GKE_SPACES_URL: spaces.gke.alphabibber.com
  GKE_WEBSOCKET_URL: websocket.gke.alphabibber.com
  GKE_WEBSOCKET_PORT: 8085
  GKE_SPACES_PORT: 8081
  GKE_FRONTEND_PORT: 80
  WEBSOCKET_TIMEOUT: 28800
  GKE_FRONTEND_REPLICAS: 1
  GKE_WEBSOCKET_REPLICAS: 1
  GKE_SPACES_REPLICAS: 1
  TAG: 1.0.

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven spaces-service
        run: mvn clean -f ./spaces-service/pom.xml package -DskipTests
      - name: Build with Maven websocket-server
        run: mvn clean -f ./websocket-service/pom.xml package -DskipTests

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
           service_account_key: ${{ secrets.GKE_SA_KEY }}
           project_id: ${{ secrets.GKE_PROJECT }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Configure docker
        run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - name: Get the GKE credentials to deploy
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      - name: Build frontend image
        run: |-
          docker build \
          --file ./frontend/Dockerfile \
          --tag "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$TAG$GITHUB_RUN_NUMBER" \
          --build-arg REACT_APP_SIGNAL_URL=$GKE_WEBSOCKET_URL \
          --build-arg REACT_APP_SPACES_URL=$GKE_SPACES_URL \
          ./frontend
      # Build the Docker image
#      - name: Build landingpage image
#        run: |-
#          docker build \
#          --file ./landingpage/Dockerfile
#          --tag "gcr.io/$PROJECT_ID/$LANDINGPAGE_IMAGE:$TAG" \
#          .
      # Build the Docker image
#      - name: Build presentation image
#        run: |-
#          docker build \
#          --file ./presentation/Dockerfile
#          --tag "gcr.io/$PROJECT_ID/$PRESENTATION_IMAGE:$TAG" \
#          .
#       Build the Docker image
      - name: Build websocket-service image
        run: |-
          docker build \
          --file ./websocket-service/Dockerfile \
          --tag "gcr.io/$PROJECT_ID/$WEBSOCKET_IMAGE:$TAG$GITHUB_RUN_NUMBER" \
          --build-arg SPACES_URL=$GKE_SPACES_URL \
          --build-arg VIRTUAL_PORT=$GKE_WEBSOCKET_PORT \
          ./websocket-service
#       Build the Docker image
      - name: Build spacesService image
        run: |-
          docker build \
          --file ./spaces-service/Dockerfile \
          --tag "gcr.io/$PROJECT_ID/$SPACES_IMAGE:$TAG$GITHUB_RUN_NUMBER" \
          --build-arg VIRTUAL_PORT=$GKE_SPACES_PORT \
          ./spaces-service

      - name: Publish frontend Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$TAG$GITHUB_RUN_NUMBER"
#      - name: Publish landingpage Docker Image to GCR
#        run: |-
#          docker push "gcr.io/$PROJECT_ID/$LANDINGPAGE_IMAGE:$TAG"
#      - name: Publish presentation Docker Image to GCR
#        run: |-
#          docker push "gcr.io/$PROJECT_ID/$PRESENTATION_IMAGE:$TAG"
      - name: Publish signalingServer Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$WEBSOCKET_IMAGE:$TAG$GITHUB_RUN_NUMBER"
      - name: Publish spacesServer Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$SPACES_IMAGE:$TAG$GITHUB_RUN_NUMBER"

#      - name: Set up Kustomize
#        run: |-
#          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
#          chmod u+x ./kustomize

      - name: pipe yaml files, replace env vars and apply to kubernetes
        run: cat deployment.yaml service.yaml ingress.yaml | sed "s/\bGKE_FRONTEND_URL\b/$GKE_FRONTEND_URL/g;
          s/\bGKE_SPACES_URL\b/$GKE_SPACES_URL/g;
          s/\bGKE_WEBSOCKET_URL\b/$GKE_WEBSOCKET_URL/g;
          s/\bGKE_WEBSOCKET_PORT\b/$GKE_WEBSOCKET_PORT/g;
          s/\bGKE_SPACES_PORT\b/$GKE_SPACES_PORT/g;
          s/\bGKE_FRONTEND_PORT\b/$GKE_FRONTEND_PORT/g;
          s/\bWEBSOCKET_TIMEOUT\b/$WEBSOCKET_TIMEOUT/g;
          s/\bGKE_FRONTEND_REPLICAS\b/$GKE_FRONTEND_REPLICAS/g;
          s/\bGKE_WEBSOCKET_REPLICAS\b/$GKE_WEBSOCKET_REPLICAS/g;
          s/\bPROJECT_ID\b/$PROJECT_ID/g;
          s/\bFRONTEND_IMAGE\b/$FRONTEND_IMAGE/g;
          s/\bWEBSOCKET_IMAGE\b/$WEBSOCKET_IMAGE/g;
          s/\bSPACES_IMAGE\b/$SPACES_IMAGE/g;
          s/\bTAG\b/$TAG$GITHUB_RUN_NUMBER/g;
          s/\bGKE_SPACES_REPLICAS\b/$GKE_SPACES_REPLICAS/g" | kubectl apply -f -

#      - name: pipe yaml files, replace env vars and apply to kubernetes
#        run: ./kustomize build . | kubectl apply -f service.yaml

#      - name: Switch to staging cluster
#        run: kubectl config use-context alphabibber-gke-prod
#      - uses: swdotcom/update-and-apply-kubernetes-configs@v1.2.0
#        with:
#          k8-config-file-paths: deployment.yaml service.yaml ingress.yaml
#          replacement-method: defined

#      - name: Deploy frontend Image to GKE cluster
#        run: |-
#          ./kustomize edit set image gcr.io/PROJECT_ID/FRONTEND_IMAGE:TAG=gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$TAG
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout status deployment/$FRONTEND_DEPLOYMENT_NAME
#          ./kustomize edit set image gcr.io/PROJECT_ID/WEBSOCKET_IMAGE:TAG=gcr.io/$PROJECT_ID/$WEBSOCKET_IMAGE:$TAG
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout status deployment/$WEBSOCKET_DEPLOYMENT_NAME
#          ./kustomize edit set image gcr.io/PROJECT_ID/SPACES_IMAGE:TAG=gcr.io/$PROJECT_ID/$SPACES_IMAGE:$TAG
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout status deployment/$SPACES_DEPLOYMENT_NAME
#          kubectl get services -o wide

#      - name: Deploy landingpage Image to GKE cluster
#        run: |-
#          ./kustomize edit set image gcr.io/PROJECT_ID/LANDINGPAGE_IMAGE:TAG=gcr.io/$PROJECT_ID/$LANDINGPAGE_IMAGE:$TAG
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout status deployment/$LANDINGPAGE_DEPLOYMENT_NAME
#          kubectl get services -o wide

#      - name: Deploy presentation Image to GKE cluster
#        run: |-
#          ./kustomize edit set image gcr.io/PROJECT_ID/PRESENTATION_IMAGE:TAG=gcr.io/$PROJECT_ID/$PRESENTATION_IMAGE:$TAG
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout status deployment/$PRESENTATION_DEPLOYMENT_NAME
#          kubectl get services -o wide